services:
  db:
    image: postgres:16
    container_name: agenda_db_dev
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: agenda_dev
    ports:
      - "5432:5432"
    volumes:
      - pgdata_dev:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:9
    container_name: agenda_pgadmin_dev
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: "True"
      PGADMIN_CONFIG_CONSOLE_LOG_LEVEL: "10"   # DEBUG no dev
    ports:
      - "5050:80"          # acesso em http://localhost:5050
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./servers.json:/pgadmin4/servers.json:ro

  mailhog:
    image: mailhog/mailhog
    container_name: agenda_mailhog_dev
    ports:
      - "8025:8025"   # UI web
      - "1025:1025"   # SMTP

  reminder-cron:
    image: python:3.12-slim
    container_name: agenda_reminder_cron
    working_dir: /app
    env_file:
      - .env.dev
    volumes:
      - ./:/app
    command: bash -lc 'pip install --no-cache-dir poetry && poetry install --only main --no-root && echo "0 9 * * * poetry run python -m app.jobs.remind_t24 >> /var/log/reminders.log 2>&1" > /etc/cron.d/reminders && chmod 0644 /etc/cron.d/reminders && crontab /etc/cron.d/reminders && cron -f'
    depends_on:
      - db
      - mailhog

volumes:
  pgdata_dev:
  pgadmin_data:
