"""user: change table name

Revision ID: 663f34bb7879
Revises: a62faf415fa7
Create Date: 2025-09-05 03:01:59.042003

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "663f34bb7879"
down_revision: str | Sequence[str] | None = "a62faf415fa7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("user", "users")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("users", "user")
    # ### end Alembic commands ###
